services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orchestrator
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./controlplane/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orchestrator"]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10

  controlplane-1:
    build: ./controlplane
    container_name: controlplane-1
    environment:
      DATABASE_URL: postgres://orchestrator:orchestrator@postgres:5432/orchestrator
      REDIS_URL: redis://redis:6379/0
      REPLICA_ID: controlplane-1
    ports:
      - "8001:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  controlplane-2:
    build: ./controlplane
    container_name: controlplane-2
    environment:
      DATABASE_URL: postgres://orchestrator:orchestrator@postgres:5432/orchestrator
      REDIS_URL: redis://redis:6379/0
      REPLICA_ID: controlplane-2
    ports:
      - "8002:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  controlplane-3:
    build: ./controlplane
    container_name: controlplane-3
    environment:
      DATABASE_URL: postgres://orchestrator:orchestrator@postgres:5432/orchestrator
      REDIS_URL: redis://redis:6379/0
      REPLICA_ID: controlplane-3
    ports:
      - "8003:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: ./worker
    environment:
      REDIS_URL: redis://redis:6379/0
      CONTROL_PLANE_URLS: "http://controlplane-1:8000,http://controlplane-2:8000,http://controlplane-3:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      controlplane-1:
        condition: service_started
      controlplane-2:
        condition: service_started
      controlplane-3:
        condition: service_started

volumes:
  pgdata:
 
